server:
  port: 8004

spring:
  mvc:
    view:
      prefix: /views/
      suffix: .html

  thymeleaf:
    cache: false

  datasource:
    name: ibookingdb
    url: jdbc:h2:mem:ibookingdb
    username: sa
    password: test123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.h2.Driver

  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      mode: always
  messages:
    encoding: UTF-8
    basename: static/i18n/messages

mybatis:
  mapper-locations: classpath:com.huawei.ibooking.mapper/*.xml
  type-aliases-package: com.huawei.ibooking.model

logging:
  level:
    com.huawei.ibooking: debug
